/**
 * This file was generated from EmailManager.xml
 * WARNING: All changes made to this file will be overwritten
 * @author Mendix Widgets Framework Team
 */
import { CSSProperties } from "react";
import { ActionValue, EditableValue, ListValue, ListActionValue, ListAttributeValue } from "mendix";
import { Big } from "big.js";

export interface EmailManagerContainerProps {
    name: string;
    class: string;
    style?: CSSProperties;
    tabIndex?: number;
    emailList?: ListValue;
    subjectAttribute?: ListAttributeValue<string>;
    senderAttribute?: ListAttributeValue<string>;
    dateAttribute?: ListAttributeValue<Date>;
    snippetAttribute?: ListAttributeValue<string>;
    bodyAttribute?: ListAttributeValue<string>;
    isReadAttribute?: ListAttributeValue<boolean>;
    groupCategoryAttribute?: ListAttributeValue<string>;
    toAttribute?: ListAttributeValue<string>;
    ccAttribute?: ListAttributeValue<string>;
    folderAttribute?: ListAttributeValue<string>;
    draftTo?: EditableValue<string>;
    draftCc?: EditableValue<string>;
    draftSubject?: EditableValue<string>;
    draftBody?: EditableValue<string>;
    partnerList?: ListValue;
    partnerCaptionAttr?: ListAttributeValue<string>;
    onPartnerChangeAction?: ListActionValue;
    selectedPartnerList?: ListValue;
    selectedPartnerCaptionAttr?: ListAttributeValue<string>;
    partnerRecipientList?: ListValue;
    partnerRecipientCaptionAttr?: ListAttributeValue<string>;
    onPartnerRecipientChangeAction?: ListActionValue;
    selectedPartnerRecipientList?: ListValue;
    selectedPartnerRecipientCaptionAttr?: ListAttributeValue<string>;
    khdaRecipientList?: ListValue;
    khdaRecipientCaptionAttr?: ListAttributeValue<string>;
    onKhdaChangeAction?: ListActionValue;
    selectedKhdaList?: ListValue;
    selectedKhdaCaptionAttr?: ListAttributeValue<string>;
    selectedRecipientList?: ListValue;
    selectedRecipientCaptionAttr?: ListAttributeValue<string>;
    onRemoveRecipientAction?: ListActionValue;
    onConfirmRecipientsAction?: ActionValue;
    draftExternalEmails?: EditableValue<string>;
    ccPartnerList?: ListValue;
    ccPartnerCaptionAttr?: ListAttributeValue<string>;
    onCcPartnerChangeAction?: ListActionValue;
    ccSelectedPartnerList?: ListValue;
    ccSelectedPartnerCaptionAttr?: ListAttributeValue<string>;
    ccPartnerRecipientList?: ListValue;
    ccPartnerRecipientCaptionAttr?: ListAttributeValue<string>;
    ccPartnerRecipientSubtitleAttr?: ListAttributeValue<string>;
    onCcPartnerRecipientChangeAction?: ListActionValue;
    ccSelectedPartnerRecipientList?: ListValue;
    ccSelectedPartnerRecipientCaptionAttr?: ListAttributeValue<string>;
    ccSelectedRecipientList?: ListValue;
    ccSelectedRecipientCaptionAttr?: ListAttributeValue<string>;
    onRemoveCcRecipientAction?: ListActionValue;
    onConfirmCcRecipientsAction?: ActionValue;
    draftExternalCcEmails?: EditableValue<string>;
    ccPartnershipEmailToggle?: EditableValue<boolean>;
    attachmentList?: ListValue;
    attachmentNameAttribute?: ListAttributeValue<string>;
    attachmentSizeAttribute?: ListAttributeValue<Big>;
    onDownloadAttachmentAction?: ListActionValue;
    onDownloadAllAttachmentsAction?: ActionValue;
    onAttachFileAction?: ActionValue;
    onFetchEmailsAction?: ActionValue;
    onCreateNewAction?: ActionValue;
    onReplyAction?: ActionValue;
    onSendAction?: ActionValue;
    onSaveDraftAction?: ActionValue;
    onEmailSelectAction?: ListActionValue;
}

export interface EmailManagerPreviewProps {
    /**
     * @deprecated Deprecated since version 9.18.0. Please use class property instead.
     */
    className: string;
    class: string;
    style: string;
    styleObject?: CSSProperties;
    readOnly: boolean;
    renderMode: "design" | "xray" | "structure";
    translate: (text: string) => string;
    emailList: {} | { caption: string } | { type: string } | null;
    subjectAttribute: string;
    senderAttribute: string;
    dateAttribute: string;
    snippetAttribute: string;
    bodyAttribute: string;
    isReadAttribute: string;
    groupCategoryAttribute: string;
    toAttribute: string;
    ccAttribute: string;
    folderAttribute: string;
    draftTo: string;
    draftCc: string;
    draftSubject: string;
    draftBody: string;
    partnerList: {} | { caption: string } | { type: string } | null;
    partnerCaptionAttr: string;
    onPartnerChangeAction: {} | null;
    selectedPartnerList: {} | { caption: string } | { type: string } | null;
    selectedPartnerCaptionAttr: string;
    partnerRecipientList: {} | { caption: string } | { type: string } | null;
    partnerRecipientCaptionAttr: string;
    onPartnerRecipientChangeAction: {} | null;
    selectedPartnerRecipientList: {} | { caption: string } | { type: string } | null;
    selectedPartnerRecipientCaptionAttr: string;
    khdaRecipientList: {} | { caption: string } | { type: string } | null;
    khdaRecipientCaptionAttr: string;
    onKhdaChangeAction: {} | null;
    selectedKhdaList: {} | { caption: string } | { type: string } | null;
    selectedKhdaCaptionAttr: string;
    selectedRecipientList: {} | { caption: string } | { type: string } | null;
    selectedRecipientCaptionAttr: string;
    onRemoveRecipientAction: {} | null;
    onConfirmRecipientsAction: {} | null;
    draftExternalEmails: string;
    ccPartnerList: {} | { caption: string } | { type: string } | null;
    ccPartnerCaptionAttr: string;
    onCcPartnerChangeAction: {} | null;
    ccSelectedPartnerList: {} | { caption: string } | { type: string } | null;
    ccSelectedPartnerCaptionAttr: string;
    ccPartnerRecipientList: {} | { caption: string } | { type: string } | null;
    ccPartnerRecipientCaptionAttr: string;
    ccPartnerRecipientSubtitleAttr: string;
    onCcPartnerRecipientChangeAction: {} | null;
    ccSelectedPartnerRecipientList: {} | { caption: string } | { type: string } | null;
    ccSelectedPartnerRecipientCaptionAttr: string;
    ccSelectedRecipientList: {} | { caption: string } | { type: string } | null;
    ccSelectedRecipientCaptionAttr: string;
    onRemoveCcRecipientAction: {} | null;
    onConfirmCcRecipientsAction: {} | null;
    draftExternalCcEmails: string;
    ccPartnershipEmailToggle: string;
    attachmentList: {} | { caption: string } | { type: string } | null;
    attachmentNameAttribute: string;
    attachmentSizeAttribute: string;
    onDownloadAttachmentAction: {} | null;
    onDownloadAllAttachmentsAction: {} | null;
    onAttachFileAction: {} | null;
    onFetchEmailsAction: {} | null;
    onCreateNewAction: {} | null;
    onReplyAction: {} | null;
    onSendAction: {} | null;
    onSaveDraftAction: {} | null;
    onEmailSelectAction: {} | null;
}
